const $=id=>document.getElementById(id);let token='';let scanToken='';let scanPoll=null;
function requireConsent(){if(!$('localConsent').checked){throw new Error('Confirm authorization before running local checks')}};
function setLocalMode(enabled){document.querySelectorAll('[data-local-panel]').forEach(panel=>panel.classList.toggle('enabled',enabled));$('localMode').textContent=enabled?'Local mode enabled':'Local mode is off';$('localMode').classList.toggle('enabled',enabled);$('agentStatus').innerHTML=enabled?'<i></i> Ready to connect local services':'<i></i> Local agent unavailable';}
setLocalMode(false);
if($('localConsent'))$('localConsent').onchange=()=>setLocalMode($('localConsent').checked);
async function readResponse(response, fallback){let data;try{data=await response.json();}catch(error){throw new Error(`${fallback} returned an invalid response`)}if(!response.ok)throw new Error(data.error||fallback);return data}
async function request(path){return readResponse(await fetch(`http://127.0.0.1:8765${path}`,{headers:{'X-AlfaSec-Token':token}}),'Agent request failed')}
async function scanRequest(path, options={}){return readResponse(await fetch(`http://127.0.0.1:8775${path}`,{...options,headers:{'Content-Type':'application/json','X-AlfaSec-Token':scanToken}}),'Scan service request failed')}
function show(id,data){$(id).textContent=JSON.stringify(data,null,2)}
$('connect').onclick=async()=>{try{requireConsent();token=$('token').value.trim();const data=await request('/health');$('agentStatus').textContent='Agent connected';$('agentStatus').className='status connected';$('statusText').textContent=`${data.agent} ready · loopback-only scope`;}catch(e){token='';$('statusText').textContent=e.message;}};
$('ports').onclick=async()=>{try{requireConsent();show('portResult',await request(`/scan/ports?host=127.0.0.1&start=${encodeURIComponent($('portStart').value)}&end=${encodeURIComponent($('portEnd').value)}`));}catch(e){show('portResult',{error:e.message});}};
$('headers').onclick=async()=>{try{requireConsent();show('headerResult',await request(`/scan/http-headers?url=${encodeURIComponent($('url').value)}`));}catch(e){show('headerResult',{error:e.message});}};
$('tls').onclick=async()=>{try{requireConsent();show('tlsResult',await request(`/scan/tls?host=127.0.0.1&port=${encodeURIComponent($('tlsPort').value)}`));}catch(e){show('tlsResult',{error:e.message});}};
$('dns').onclick=async()=>{try{requireConsent();show('dnsResult',await request('/scan/dns?host=localhost'));}catch(e){show('dnsResult',{error:e.message});}};
$('startScan').onclick=async()=>{try{requireConsent();scanToken=$('scanToken').value.trim();if(scanPoll){clearTimeout(scanPoll);scanPoll=null;}const job=await scanRequest('/scan/start',{method:'POST',body:JSON.stringify({project_path:$('projectPath').value.trim()})});$('scanStatus').textContent=`Scan ${job.id} queued`;const poll=async()=>{try{const status=await scanRequest(`/scan/status?id=${encodeURIComponent(job.id)}`);$('scanStatus').textContent=`Scan ${job.id}: ${status.status}`;if(status.status==='complete'){show('scanResult',await scanRequest(`/scan/result?id=${encodeURIComponent(job.id)}`));scanPoll=null;}else if(['failed','timed_out'].includes(status.status)){show('scanResult',{error:status.error||`Scan ${status.status}`});scanPoll=null;}else{scanPoll=setTimeout(poll,1000);}}catch(e){$('scanStatus').textContent=e.message;scanPoll=null;}};poll();}catch(e){$('scanStatus').textContent=e.message;}};
$('refreshProjects').onclick=async()=>{try{const data=await scanRequest('/projects');show('projectResult',data);}catch(e){show('projectResult',{error:e.message});}};
$('loadSummary').onclick=async()=>{try{const id=encodeURIComponent($('summaryProjectId').value.trim());const [summary,governance]=await Promise.all([scanRequest(`/projects/summary?id=${id}`),scanRequest(`/projects/governance?id=${id}`)]);show('summaryResult',{summary,governance});}catch(e){show('summaryResult',{error:e.message});}};
$('saveWorkflow').onclick=async()=>{try{const projectId=$('workflowProjectId').value.trim();show('workflowResult',await scanRequest('/projects/finding-action',{method:'POST',body:JSON.stringify({project_id:projectId,fingerprint:$('workflowFingerprint').value.trim(),state:$('workflowState').value,owner:$('workflowOwner').value.trim()||null,due_date:null,expires_at:null,rationale:$('workflowRationale').value.trim()||null})}));}catch(e){show('workflowResult',{error:e.message});}};
$('verifyRemediation').onclick=async()=>{try{show('remediationResult',await scanRequest('/projects/remediation-verify',{method:'POST',body:JSON.stringify({project_id:$('remediationProjectId').value.trim(),plan_path:$('remediationPlanPath').value.trim()||null})}));}catch(e){show('remediationResult',{error:e.message});}};
